# Generated by Django 4.2.2 on 2023-08-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.company'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='static/uploads/events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mentor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.mentor'),
        ),
    ]
