# Generated by Django 4.2.2 on 2023-08-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('events', '0003_remove_event_company_alter_event_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='mentor',
        ),
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.company'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakerDescription',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='speakerDesignation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='speakerImage',
            field=models.ImageField(null=True, upload_to='static/uploads/events/speaker'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakerName',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='static/uploads/events/banner'),
        ),
    ]
