# Generated by Django 4.2.2 on 2023-08-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_mentor_event_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speakerDesignation',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
