# Generated by Django 4.2.4 on 2023-08-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="company",),
        migrations.RemoveField(model_name="job", name="skills_required",),
        migrations.RemoveField(model_name="jobskill", name="job",),
        migrations.RemoveField(model_name="jobskill", name="skill",),
        migrations.DeleteModel(name="Company",),
        migrations.DeleteModel(name="Job",),
        migrations.DeleteModel(name="JobSkill",),
        migrations.DeleteModel(name="Skill",),
    ]
