# Generated by Django 4.2.2 on 2023-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='MinExperience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
