# Generated by Django 4.2.2 on 2023-08-05 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_minexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='perks',
            field=models.CharField(default='Salary', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='postedDate',
            field=models.DateField(default=datetime.date(2023, 8, 5)),
        ),
        migrations.AddField(
            model_name='job',
            name='startDate',
            field=models.DateField(default=datetime.date(2023, 8, 5)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='whoCanApply',
            field=models.CharField(default='Anyone', max_length=150),
            preserve_default=False,
        ),
    ]
