# Generated by Django 4.2.2 on 2023-08-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_candidate_age'),
        ('jobs', '0003_job_openings_job_perks_job_posteddate_job_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
