# Generated by Django 4.2.4 on 2023-08-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="internship", name="company",),
        migrations.RemoveField(model_name="internship", name="skills_required",),
        migrations.RemoveField(model_name="internshipskill", name="internship",),
        migrations.RemoveField(model_name="internshipskill", name="skill",),
        migrations.DeleteModel(name="Company",),
        migrations.DeleteModel(name="Internship",),
        migrations.DeleteModel(name="InternshipSkill",),
        migrations.DeleteModel(name="Skill",),
    ]
