# Generated by Django 4.2.2 on 2023-07-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('email', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=10)),
                ('age', models.ImageField(null=True, upload_to='')),
                ('resume', models.FileField(null=True, upload_to='static/uploads/resume')),
                ('pp', models.ImageField(null=True, upload_to='static/uploads/pp')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('email', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.ImageField(null=True, upload_to='static/uploads/logo')),
            ],
        ),
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('email', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('pp', models.ImageField(null=True, upload_to='static/uploads/pp')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
