# Generated by Django 4.2.4 on 2023-08-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="skill", new_name="skills",),
    ]
